// jsPDF is imported dynamically inside each export function to prevent
// jspdf.node.min.js from running Node.js-specific side-effects at module
// evaluation time, which crashes the browser bundle on import.

interface PostData {
  title: string
  domain: string
  description: string
  authorName: string
  authorRole: string
  projectStage: string
  collaborationType: string
  city: string
  country: string
  expiryDate: string
  expertiseRequired: string
}

interface SummaryData {
  postTitle: string
  topics: string[]
  nextSteps: string[]
  openQuestions: string[]
  generatedAt: string
}

const STAGE_LABELS: Record<string, string> = {
  idea: 'Idea',
  concept_validation: 'Concept Validation',
  prototype: 'Prototype',
  pilot: 'Pilot',
  pre_deployment: 'Pre-deployment',
}

const COLLAB_LABELS: Record<string, string> = {
  advisor: 'Advisor',
  co_founder: 'Co-Founder',
  research_partner: 'Research Partner',
  contract: 'Contract',
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function addHeader(doc: any, title: string) {
  doc.setFillColor(54, 33, 62)
  doc.rect(0, 0, 210, 18, 'F')
  doc.setTextColor(255, 255, 255)
  doc.setFontSize(10)
  doc.setFont('helvetica', 'bold')
  doc.text('HEALTH AI Co-Creation Platform', 10, 11)
  doc.setFontSize(8)
  doc.setFont('helvetica', 'normal')
  doc.text(new Date().toLocaleDateString('en-GB'), 200, 11, { align: 'right' })
  doc.setTextColor(54, 33, 62)
  doc.setFontSize(16)
  doc.setFont('helvetica', 'bold')
  doc.text(title, 10, 32)
  doc.setDrawColor(111, 184, 196)
  doc.setLineWidth(0.5)
  doc.line(10, 35, 200, 35)
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function addField(doc: any, label: string, value: string, y: number): number {
  doc.setFontSize(8)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(111, 131, 120)
  doc.text(label.toUpperCase(), 10, y)
  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(54, 33, 62)
  const lines = doc.splitTextToSize(value, 185)
  doc.text(lines, 10, y + 5)
  return y + 5 + (lines.length * 5) + 4
}

export async function exportPostToPdf(post: PostData): Promise<void> {
  const { default: jsPDF } = await import('jspdf')
  const doc = new jsPDF({ unit: 'mm', format: 'a4' })
  addHeader(doc, post.title)

  let y = 42
  y = addField(doc, 'Author', `${post.authorName} (${post.authorRole === 'engineer' ? 'Engineer' : 'Healthcare Professional'})`, y)
  y = addField(doc, 'Domain', post.domain, y)
  y = addField(doc, 'Expertise Required', post.expertiseRequired, y)
  y = addField(doc, 'Project Stage', STAGE_LABELS[post.projectStage] ?? post.projectStage, y)
  y = addField(doc, 'Collaboration Type', COLLAB_LABELS[post.collaborationType] ?? post.collaborationType, y)
  y = addField(doc, 'Location', `${post.city}, ${post.country}`, y)
  y = addField(doc, 'Listing Expires', new Date(post.expiryDate).toLocaleDateString('en-GB'), y)
  y += 3
  addField(doc, 'Description', post.description, y)

  doc.setFontSize(7)
  doc.setTextColor(180, 180, 180)
  doc.text('Generated by HEALTH AI Co-Creation Platform', 105, 290, { align: 'center' })

  const filename = post.title.replace(/[^a-z0-9]/gi, '-').toLowerCase().slice(0, 40)
  doc.save(`healthai-post-${filename}.pdf`)
}

export async function exportSummaryToPdf(summary: SummaryData): Promise<void> {
  const { default: jsPDF } = await import('jspdf')
  const doc = new jsPDF({ unit: 'mm', format: 'a4' })
  addHeader(doc, `Meeting Summary: ${summary.postTitle}`)

  let y = 42
  doc.setFontSize(8)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(111, 131, 120)
  doc.text(`Generated ${new Date(summary.generatedAt).toLocaleDateString('en-GB')}`, 10, y)
  y += 8

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const addBulletSection = (title: string, items: string[], bulletColor: [number, number, number]) => {
    if (items.length === 0) return
    doc.setFontSize(10)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(54, 33, 62)
    doc.text(title, 10, y)
    y += 6
    items.forEach(item => {
      doc.setFillColor(...bulletColor)
      doc.circle(13, y - 1, 1, 'F')
      doc.setFontSize(9)
      doc.setFont('helvetica', 'normal')
      doc.setTextColor(55, 65, 81)
      const lines = doc.splitTextToSize(item, 178)
      doc.text(lines, 16, y)
      y += lines.length * 5 + 2
    })
    y += 4
  }

  addBulletSection('Topics Discussed', summary.topics, [111, 184, 196])
  addBulletSection('Next Steps', summary.nextSteps, [74, 222, 128])
  addBulletSection('Open Questions', summary.openQuestions, [251, 191, 36])

  doc.setFontSize(7)
  doc.setTextColor(180, 180, 180)
  doc.text('AI-generated summary — HEALTH AI Co-Creation Platform', 105, 290, { align: 'center' })

  const filename = summary.postTitle.replace(/[^a-z0-9]/gi, '-').toLowerCase().slice(0, 40)
  doc.save(`healthai-meeting-summary-${filename}.pdf`)
}
